name: CI Apple sorter

# Trigger
on:
  pull_request:
    branches:
      - dev

#Acciones
jobs:
  build_docker_image:
    runs-on: ubuntu-lastest

    steps:
      - name: Check Repo
        uses: actions/checkout@v2

      - name: Loggin to dockerhub
        uses: docker/login-action@v2
        with:

          username: ${{secrets.DOCKER_USERNAME}}
          passsword: ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t gab1995/deploy-apple-sorter:v1 .

      - name: Docker Push to Dockerhub
        run: docker push gab1995/deploy-apple-sorter:v1

